# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRhF_FVq0ZPuPJttnMH07mKBDx_4RDax
"""

#  Import libraries
import tensorflow as tf
import numpy as np
from PIL import Image
from google.colab import files
import zipfile
import os

#  Upload the .zip file
print("🔺 Upload the model zip file (e.g., converted_keras.zip)")
uploaded = files.upload()
zip_filename = list(uploaded.keys())[0]

#  Unzip the file
with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall("model_files")

# Load model and labels from extracted folder
model_path = "model_files/keras_model.h5"
labels_path = "model_files/labels.txt"

model = tf.keras.models.load_model(model_path)
with open(labels_path, "r") as f:
    labels = f.read().splitlines()

#  Upload test image
print("🔺 Please upload an image to test")
image_upload = files.upload()
image_path = list(image_upload.keys())[0]

#  Prepare image and predict
def load_image(path):
    img = Image.open(path).convert("RGB").resize((224, 224))  # نحول الصورة إلى RGB
    img = np.array(img) / 255.0
    return np.expand_dims(img, axis=0)

def predict(image_path):
    image = load_image(image_path)
    prediction = model.predict(image)
    index = np.argmax(prediction)
    confidence = prediction[0][index]
    print("\n✅ Prediction Result:")
    print(f"Class: {labels[index]}")
    print(f"Confidence: {confidence:.2%}")

#  Run prediction
predict(image_path)